---
title: "hmDE"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{hmDE}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)

library(hmDE)
```

## Goal of package

## Installation

'hmDE' is under active development, you can install the development version of 'hmDE' from [GitHub](https://github.com/) with:

```{r, eval=FALSE}
# install.packages("remotes")
remotes::install_github("traitecoevo/hmDE")

library(hmDE)
```

## {hmDE} supported models

### Constant Growth - Single Individual

```{r, eval=FALSE}
# Create data
true <- c(seq(from=1, by=2.5, length.out=7))
y <- true + true*rnorm(n=7, 0, 0.02) + rnorm(n=7, 0, 0.2)

# Configure model template
const_single_ind_output <- hmDE_model("constant_single_ind") |>
  hmDE_assign_data(n_obs = length(y), #integer
                   y_obs = y, #vector length N_obs
                   obs_index = 1:7, #vector length N_obs
                   time = rep(5, times=length(y)), #Vector length N_obs
                   y_0_obs = y[1] #vector length N_ind
                   )  |>
  hmDE_run()

# Look at output
const_single_ind_output
```

### Constant Growth - Multiple Individuals

```{r, eval=FALSE}
# Create data
true <- c(seq(from=1, by=2.5, length.out=7),
          seq(from=2, by=2, length.out=7))
y <- true + true*rnorm(n=14, 0, 0.02) + rnorm(n=14, 0, 0.2)

# Configure model template
const_multi_ind_output <- hmDE_model("constant_multi_ind") |>
  hmDE_assign_data(n_obs = length(y), #integer
                   n_ind = 2, #integer
                   y_obs = y, #vector length N_obs
                   obs_index = rep(seq(from=1, to=7, by=1), times=2), #vector length N_obs
                   time = rep(5, times=length(y)), #Vector length N_obs
                   ind_id = c(rep(1, times=7), rep(2, times=7)), #Vector length N_obs
                   y_0_obs = y[c(1, 8)] #vector length N_ind
                   )  |>
  hmDE_run()

# Look at output
const_multi_ind_output
```
