// Generated by rstantools.  Do not edit by hand.

/*
    rmot is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    rmot is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with rmot.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_canham_single_ind_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 81> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 52, column 2 to column 24)",
  " (in 'string', line 53, column 2 to column 31)",
  " (in 'string', line 54, column 2 to column 43)",
  " (in 'string', line 55, column 2 to column 22)",
  " (in 'string', line 57, column 2 to column 35)",
  " (in 'string', line 87, column 2 to column 20)",
  " (in 'string', line 88, column 2 to column 24)",
  " (in 'string', line 89, column 2 to column 17)",
  " (in 'string', line 90, column 2 to column 27)",
  " (in 'string', line 91, column 2 to column 39)",
  " (in 'string', line 92, column 2 to column 18)",
  " (in 'string', line 95, column 6 to column 25)",
  " (in 'string', line 94, column 23 to line 96, column 5)",
  " (in 'string', line 94, column 4 to line 96, column 5)",
  " (in 'string', line 102, column 6 to column 62)",
  " (in 'string', line 101, column 11 to line 103, column 5)",
  " (in 'string', line 99, column 6 to column 73)",
  " (in 'string', line 100, column 6 to column 43)",
  " (in 'string', line 97, column 17 to line 101, column 5)",
  " (in 'string', line 97, column 4 to line 103, column 5)",
  " (in 'string', line 93, column 19 to line 104, column 3)",
  " (in 'string', line 93, column 2 to line 104, column 3)",
  " (in 'string', line 61, column 13 to column 18)",
  " (in 'string', line 61, column 2 to column 20)",
  " (in 'string', line 62, column 2 to column 17)",
  " (in 'string', line 63, column 2 to column 27)",
  " (in 'string', line 64, column 2 to column 39)",
  " (in 'string', line 65, column 2 to column 18)",
  " (in 'string', line 68, column 6 to column 25)",
  " (in 'string', line 67, column 23 to line 69, column 5)",
  " (in 'string', line 67, column 4 to line 69, column 5)",
  " (in 'string', line 72, column 6 to column 73)",
  " (in 'string', line 70, column 17 to line 73, column 5)",
  " (in 'string', line 70, column 4 to line 73, column 5)",
  " (in 'string', line 66, column 19 to line 74, column 3)",
  " (in 'string', line 66, column 2 to line 74, column 3)",
  " (in 'string', line 76, column 2 to column 44)",
  " (in 'string', line 79, column 2 to column 48)",
  " (in 'string', line 80, column 2 to column 34)",
  " (in 'string', line 81, column 2 to column 46)",
  " (in 'string', line 82, column 2 to column 25)",
  " (in 'string', line 84, column 2 to column 34)",
  " (in 'string', line 42, column 2 to column 17)",
  " (in 'string', line 43, column 2 to column 12)",
  " (in 'string', line 44, column 13 to column 18)",
  " (in 'string', line 44, column 2 to column 20)",
  " (in 'string', line 45, column 16 to column 21)",
  " (in 'string', line 45, column 2 to column 23)",
  " (in 'string', line 46, column 12 to column 17)",
  " (in 'string', line 46, column 2 to column 19)",
  " (in 'string', line 47, column 2 to column 15)",
  " (in 'string', line 87, column 13 to column 18)",
  " (in 'string', line 88, column 17 to column 22)",
  " (in 'string', line 6, column 4 to line 7, column 51)",
  " (in 'string', line 5, column 30 to line 8, column 3)",
  " (in 'string', line 10, column 4 to column 12)",
  " (in 'string', line 11, column 4 to column 12)",
  " (in 'string', line 12, column 4 to column 12)",
  " (in 'string', line 13, column 4 to column 12)",
  " (in 'string', line 14, column 4 to column 15)",
  " (in 'string', line 15, column 4 to column 21)",
  " (in 'string', line 16, column 4 to column 37)",
  " (in 'string', line 17, column 4 to column 37)",
  " (in 'string', line 18, column 4 to column 33)",
  " (in 'string', line 19, column 4 to column 67)",
  " (in 'string', line 20, column 4 to column 17)",
  " (in 'string', line 9, column 51 to line 21, column 3)",
  " (in 'string', line 23, column 4 to column 14)",
  " (in 'string', line 24, column 4 to column 18)",
  " (in 'string', line 25, column 4 to column 15)",
  " (in 'string', line 26, column 4 to column 24)",
  " (in 'string', line 27, column 4 to column 17)",
  " (in 'string', line 28, column 4 to column 14)",
  " (in 'string', line 31, column 6 to column 59)",
  " (in 'string', line 33, column 6 to column 52)",
  " (in 'string', line 35, column 6 to column 43)",
  " (in 'string', line 29, column 30 to line 36, column 5)",
  " (in 'string', line 29, column 4 to line 36, column 5)",
  " (in 'string', line 37, column 4 to column 17)",
  " (in 'string', line 22, column 62 to line 38, column 3)"};
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>* = nullptr>
stan::promote_args_t<T0__, stan::base_type_t<T1__>>
DE(const T0__& y, const T1__& pars_arg__, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_stan_scalar<T2__>>* = nullptr>
stan::promote_args_t<T0__, stan::base_type_t<T1__>, T2__>
rk4_step(const T0__& y, const T1__& pars_arg__, const T2__& interval,
         std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
stan::promote_args_t<T0__, stan::base_type_t<T1__>, T2__, T3__>
rk4(const T0__& y, const T1__& pars_arg__, const T2__& interval, const T3__&
    step_size, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>*>
stan::promote_args_t<T0__, stan::base_type_t<T1__>>
DE(const T0__& y, const T1__& pars_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
                             stan::base_type_t<T1__>>;
  int current_statement__ = 0;
  const auto& pars = stan::math::to_ref(pars_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 54;
    return (stan::model::rvalue(pars, "pars", stan::model::index_uni(1)) *
           stan::math::exp((-0.5 *
             stan::math::pow(
               (stan::math::log((y /
                  stan::model::rvalue(pars, "pars", stan::model::index_uni(2))))
               /
               stan::model::rvalue(pars, "pars", stan::model::index_uni(3))),
               2))));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_stan_scalar<T2__>>*>
stan::promote_args_t<T0__, stan::base_type_t<T1__>, T2__>
rk4_step(const T0__& y, const T1__& pars_arg__, const T2__& interval,
         std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
                             stan::base_type_t<T1__>, T2__>;
  int current_statement__ = 0;
  const auto& pars = stan::math::to_ref(pars_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ k1 = DUMMY_VAR__;
    local_scalar_t__ k2 = DUMMY_VAR__;
    local_scalar_t__ k3 = DUMMY_VAR__;
    local_scalar_t__ k4 = DUMMY_VAR__;
    local_scalar_t__ y_hat = DUMMY_VAR__;
    current_statement__ = 61;
    k1 = DE(y, pars, pstream__);
    current_statement__ = 62;
    k2 = DE((y + ((interval * k1) / 2.0)), pars, pstream__);
    current_statement__ = 63;
    k3 = DE((y + ((interval * k2) / 2.0)), pars, pstream__);
    current_statement__ = 64;
    k4 = DE((y + (interval * k3)), pars, pstream__);
    current_statement__ = 65;
    y_hat = (y + (((1.0 / 6.0) * (((k1 + (2.0 * k2)) + (2.0 * k3)) + k4)) *
      interval));
    current_statement__ = 66;
    return y_hat;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
stan::promote_args_t<T0__, stan::base_type_t<T1__>, T2__, T3__>
rk4(const T0__& y, const T1__& pars_arg__, const T2__& interval, const T3__&
    step_size, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
                             stan::base_type_t<T1__>, T2__, T3__>;
  int current_statement__ = 0;
  const auto& pars = stan::math::to_ref(pars_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int steps = std::numeric_limits<int>::min();
    local_scalar_t__ duration = DUMMY_VAR__;
    local_scalar_t__ y_hat = DUMMY_VAR__;
    local_scalar_t__ step_size_temp = DUMMY_VAR__;
    current_statement__ = 72;
    duration = 0;
    current_statement__ = 73;
    y_hat = y;
    current_statement__ = 78;
    while (stan::math::logical_lt(duration, interval)) {
      current_statement__ = 74;
      step_size_temp = stan::math::min(
                         (Eigen::Matrix<local_scalar_t__,1,-1>(2) <<
                                                                    step_size,
                                                                    (interval
                                                                    -
                                                                    duration)).finished());
      current_statement__ = 75;
      y_hat = rk4_step(y_hat, pars, step_size_temp, pstream__);
      current_statement__ = 76;
      duration = (duration + step_size_temp);
    }
    current_statement__ = 79;
    return y_hat;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_canham_single_ind final : public model_base_crtp<model_canham_single_ind> {
private:
  double step_size;
  int n_obs;
  std::vector<double> y_obs;
  std::vector<int> obs_index;
  std::vector<double> time;
  double y_0_obs;
public:
  ~model_canham_single_ind() {}
  model_canham_single_ind(stan::io::var_context& context__, unsigned int
                          random_seed__ = 0, std::ostream*
                          pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_canham_single_ind_namespace::model_canham_single_ind";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 43;
      context__.validate_dims("data initialization", "step_size", "double",
        std::vector<size_t>{});
      step_size = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 43;
      step_size = context__.vals_r("step_size")[(1 - 1)];
      current_statement__ = 44;
      context__.validate_dims("data initialization", "n_obs", "int",
        std::vector<size_t>{});
      n_obs = std::numeric_limits<int>::min();
      current_statement__ = 44;
      n_obs = context__.vals_i("n_obs")[(1 - 1)];
      current_statement__ = 45;
      stan::math::validate_non_negative_index("y_obs", "n_obs", n_obs);
      current_statement__ = 46;
      context__.validate_dims("data initialization", "y_obs", "double",
        std::vector<size_t>{static_cast<size_t>(n_obs)});
      y_obs = std::vector<double>(n_obs,
                std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 46;
      y_obs = context__.vals_r("y_obs");
      current_statement__ = 47;
      stan::math::validate_non_negative_index("obs_index", "n_obs", n_obs);
      current_statement__ = 48;
      context__.validate_dims("data initialization", "obs_index", "int",
        std::vector<size_t>{static_cast<size_t>(n_obs)});
      obs_index = std::vector<int>(n_obs, std::numeric_limits<int>::min());
      current_statement__ = 48;
      obs_index = context__.vals_i("obs_index");
      current_statement__ = 49;
      stan::math::validate_non_negative_index("time", "n_obs", n_obs);
      current_statement__ = 50;
      context__.validate_dims("data initialization", "time", "double",
        std::vector<size_t>{static_cast<size_t>(n_obs)});
      time = std::vector<double>(n_obs,
               std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 50;
      time = context__.vals_r("time");
      current_statement__ = 51;
      context__.validate_dims("data initialization", "y_0_obs", "double",
        std::vector<size_t>{});
      y_0_obs = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 51;
      y_0_obs = context__.vals_r("y_0_obs")[(1 - 1)];
      current_statement__ = 52;
      stan::math::validate_non_negative_index("y_hat", "n_obs", n_obs);
      current_statement__ = 53;
      stan::math::validate_non_negative_index("Delta_hat", "n_obs", n_obs);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_canham_single_ind";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_canham_single_ind_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      local_scalar_t__ ind_y_0 = DUMMY_VAR__;
      current_statement__ = 1;
      ind_y_0 = in__.template read_constrain_lb<local_scalar_t__,
                  jacobian__>(0, lp__);
      local_scalar_t__ ind_max_growth = DUMMY_VAR__;
      current_statement__ = 2;
      ind_max_growth = in__.template read_constrain_lb<local_scalar_t__,
                         jacobian__>(0, lp__);
      local_scalar_t__ ind_diameter_at_max_growth = DUMMY_VAR__;
      current_statement__ = 3;
      ind_diameter_at_max_growth = in__.template read_constrain_lb<
                                     local_scalar_t__, jacobian__>(0, lp__);
      local_scalar_t__ ind_k = DUMMY_VAR__;
      current_statement__ = 4;
      ind_k = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      local_scalar_t__ global_error_sigma = DUMMY_VAR__;
      current_statement__ = 5;
      global_error_sigma = in__.template read_constrain_lb<local_scalar_t__,
                             jacobian__>(0, lp__);
      {
        current_statement__ = 23;
        stan::math::validate_non_negative_index("y_hat", "n_obs", n_obs);
        std::vector<local_scalar_t__> y_hat =
          std::vector<local_scalar_t__>(n_obs, DUMMY_VAR__);
        Eigen::Matrix<local_scalar_t__,-1,1> pars =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(3, DUMMY_VAR__);
        current_statement__ = 26;
        stan::model::assign(pars, ind_max_growth, "assigning variable pars",
          stan::model::index_uni(1));
        current_statement__ = 27;
        stan::model::assign(pars, ind_diameter_at_max_growth,
          "assigning variable pars", stan::model::index_uni(2));
        current_statement__ = 28;
        stan::model::assign(pars, ind_k, "assigning variable pars",
          stan::model::index_uni(3));
        current_statement__ = 36;
        for (int i = 1; i <= n_obs; ++i) {
          current_statement__ = 31;
          if (stan::math::logical_eq(
                stan::model::rvalue(obs_index, "obs_index",
                  stan::model::index_uni(i)), 1)) {
            current_statement__ = 29;
            stan::model::assign(y_hat, ind_y_0, "assigning variable y_hat",
              stan::model::index_uni(i));
          }
          current_statement__ = 34;
          if (stan::math::logical_lt(i, n_obs)) {
            current_statement__ = 32;
            stan::model::assign(y_hat,
              rk4(
                stan::model::rvalue(y_hat, "y_hat", stan::model::index_uni(i)),
                pars,
                (stan::model::rvalue(time, "time",
                   stan::model::index_uni((i + 1))) -
                stan::model::rvalue(time, "time", stan::model::index_uni(i))),
                step_size, pstream__), "assigning variable y_hat",
              stan::model::index_uni((i + 1)));
          }
        }
        current_statement__ = 37;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(y_obs, y_hat,
                         global_error_sigma));
        current_statement__ = 38;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(ind_y_0, y_0_obs,
                         global_error_sigma));
        current_statement__ = 39;
        lp_accum__.add(stan::math::lognormal_lpdf<propto__>(ind_max_growth,
                         0, 1));
        current_statement__ = 40;
        lp_accum__.add(stan::math::lognormal_lpdf<propto__>(
                         ind_diameter_at_max_growth, 3, 1));
        current_statement__ = 41;
        lp_accum__.add(stan::math::lognormal_lpdf<propto__>(ind_k, 0, 1));
        current_statement__ = 42;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(global_error_sigma,
                         0, 5));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_canham_single_ind_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      double ind_y_0 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      ind_y_0 = in__.template read_constrain_lb<local_scalar_t__,
                  jacobian__>(0, lp__);
      double ind_max_growth = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      ind_max_growth = in__.template read_constrain_lb<local_scalar_t__,
                         jacobian__>(0, lp__);
      double ind_diameter_at_max_growth =
        std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      ind_diameter_at_max_growth = in__.template read_constrain_lb<
                                     local_scalar_t__, jacobian__>(0, lp__);
      double ind_k = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      ind_k = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      double global_error_sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      global_error_sigma = in__.template read_constrain_lb<local_scalar_t__,
                             jacobian__>(0, lp__);
      out__.write(ind_y_0);
      out__.write(ind_max_growth);
      out__.write(ind_diameter_at_max_growth);
      out__.write(ind_k);
      out__.write(global_error_sigma);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      std::vector<double> y_hat =
        std::vector<double>(n_obs, std::numeric_limits<double>::quiet_NaN());
      std::vector<double> Delta_hat =
        std::vector<double>(n_obs, std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> pars =
        Eigen::Matrix<double,-1,1>::Constant(3,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 9;
      stan::model::assign(pars, ind_max_growth, "assigning variable pars",
        stan::model::index_uni(1));
      current_statement__ = 10;
      stan::model::assign(pars, ind_diameter_at_max_growth,
        "assigning variable pars", stan::model::index_uni(2));
      current_statement__ = 11;
      stan::model::assign(pars, ind_k, "assigning variable pars",
        stan::model::index_uni(3));
      current_statement__ = 22;
      for (int i = 1; i <= n_obs; ++i) {
        current_statement__ = 14;
        if (stan::math::logical_eq(
              stan::model::rvalue(obs_index, "obs_index",
                stan::model::index_uni(i)), 1)) {
          current_statement__ = 12;
          stan::model::assign(y_hat, ind_y_0, "assigning variable y_hat",
            stan::model::index_uni(i));
        }
        current_statement__ = 20;
        if (stan::math::logical_lt(i, n_obs)) {
          current_statement__ = 17;
          stan::model::assign(y_hat,
            rk4(
              stan::model::rvalue(y_hat, "y_hat", stan::model::index_uni(i)),
              pars,
              (stan::model::rvalue(time, "time",
                 stan::model::index_uni((i + 1))) -
              stan::model::rvalue(time, "time", stan::model::index_uni(i))),
              step_size, pstream__), "assigning variable y_hat",
            stan::model::index_uni((i + 1)));
          current_statement__ = 18;
          stan::model::assign(Delta_hat,
            (stan::model::rvalue(y_hat, "y_hat",
               stan::model::index_uni((i + 1))) -
            stan::model::rvalue(y_hat, "y_hat", stan::model::index_uni(i))),
            "assigning variable Delta_hat", stan::model::index_uni(i));
        } else {
          current_statement__ = 15;
          stan::model::assign(Delta_hat,
            (DE(
               stan::model::rvalue(y_hat, "y_hat", stan::model::index_uni(i)),
               pars, pstream__) *
            (stan::model::rvalue(time, "time", stan::model::index_uni(i)) -
            stan::model::rvalue(time, "time", stan::model::index_uni((i - 1))))),
            "assigning variable Delta_hat", stan::model::index_uni(i));
        }
      }
      out__.write(y_hat);
      out__.write(Delta_hat);
      out__.write(pars);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ ind_y_0 = DUMMY_VAR__;
      current_statement__ = 1;
      ind_y_0 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, ind_y_0);
      local_scalar_t__ ind_max_growth = DUMMY_VAR__;
      current_statement__ = 2;
      ind_max_growth = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, ind_max_growth);
      local_scalar_t__ ind_diameter_at_max_growth = DUMMY_VAR__;
      current_statement__ = 3;
      ind_diameter_at_max_growth = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, ind_diameter_at_max_growth);
      local_scalar_t__ ind_k = DUMMY_VAR__;
      current_statement__ = 4;
      ind_k = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, ind_k);
      local_scalar_t__ global_error_sigma = DUMMY_VAR__;
      current_statement__ = 5;
      global_error_sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, global_error_sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "ind_y_0",
        "double", std::vector<size_t>{});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "ind_max_growth",
        "double", std::vector<size_t>{});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization",
        "ind_diameter_at_max_growth", "double", std::vector<size_t>{});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "ind_k", "double",
        std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization",
        "global_error_sigma", "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ ind_y_0 = DUMMY_VAR__;
      current_statement__ = 1;
      ind_y_0 = context__.vals_r("ind_y_0")[(1 - 1)];
      out__.write_free_lb(0, ind_y_0);
      local_scalar_t__ ind_max_growth = DUMMY_VAR__;
      current_statement__ = 2;
      ind_max_growth = context__.vals_r("ind_max_growth")[(1 - 1)];
      out__.write_free_lb(0, ind_max_growth);
      local_scalar_t__ ind_diameter_at_max_growth = DUMMY_VAR__;
      current_statement__ = 3;
      ind_diameter_at_max_growth = context__.vals_r("ind_diameter_at_max_growth")[(1
        - 1)];
      out__.write_free_lb(0, ind_diameter_at_max_growth);
      local_scalar_t__ ind_k = DUMMY_VAR__;
      current_statement__ = 4;
      ind_k = context__.vals_r("ind_k")[(1 - 1)];
      out__.write_free_lb(0, ind_k);
      local_scalar_t__ global_error_sigma = DUMMY_VAR__;
      current_statement__ = 5;
      global_error_sigma = context__.vals_r("global_error_sigma")[(1 - 1)];
      out__.write_free_lb(0, global_error_sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"ind_y_0", "ind_max_growth",
                "ind_diameter_at_max_growth", "ind_k", "global_error_sigma"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"y_hat", "Delta_hat", "pars"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(n_obs)},
             std::vector<size_t>{static_cast<size_t>(n_obs)},
             std::vector<size_t>{static_cast<size_t>(3)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "ind_y_0");
    param_names__.emplace_back(std::string() + "ind_max_growth");
    param_names__.emplace_back(std::string() + "ind_diameter_at_max_growth");
    param_names__.emplace_back(std::string() + "ind_k");
    param_names__.emplace_back(std::string() + "global_error_sigma");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_hat" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "Delta_hat" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        param_names__.emplace_back(std::string() + "pars" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    param_names__.emplace_back(std::string() + "ind_y_0");
    param_names__.emplace_back(std::string() + "ind_max_growth");
    param_names__.emplace_back(std::string() + "ind_diameter_at_max_growth");
    param_names__.emplace_back(std::string() + "ind_k");
    param_names__.emplace_back(std::string() + "global_error_sigma");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_hat" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "Delta_hat" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        param_names__.emplace_back(std::string() + "pars" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"ind_y_0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ind_max_growth\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ind_diameter_at_max_growth\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ind_k\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"global_error_sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_hat\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_obs) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"Delta_hat\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_obs) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"pars\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(3) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"ind_y_0\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ind_max_growth\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ind_diameter_at_max_growth\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"ind_k\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"global_error_sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_hat\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_obs) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"Delta_hat\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_obs) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"pars\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(3) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((1 + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (((n_obs +
      n_obs) + 3));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((1 + 1) + 1) + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (((n_obs +
      n_obs) + 3));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_canham_single_ind_namespace::model_canham_single_ind;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_canham_single_ind_namespace::profiles__;
}
#endif
#endif
