// Generated by rstantools.  Do not edit by hand.

/*
    rmot is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    rmot is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with rmot.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_power_multi_ind_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 101> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 54, column 2 to column 31)",
  " (in 'string', line 55, column 2 to column 33)",
  " (in 'string', line 56, column 2 to column 33)",
  " (in 'string', line 58, column 2 to column 26)",
  " (in 'string', line 59, column 2 to column 33)",
  " (in 'string', line 60, column 2 to column 26)",
  " (in 'string', line 61, column 2 to column 33)",
  " (in 'string', line 63, column 2 to column 35)",
  " (in 'string', line 100, column 2 to column 20)",
  " (in 'string', line 101, column 2 to column 24)",
  " (in 'string', line 102, column 2 to column 17)",
  " (in 'string', line 105, column 4 to column 35)",
  " (in 'string', line 106, column 4 to column 35)",
  " (in 'string', line 107, column 4 to column 20)",
  " (in 'string', line 109, column 6 to column 36)",
  " (in 'string', line 108, column 23 to line 110, column 5)",
  " (in 'string', line 108, column 4 to line 110, column 5)",
  " (in 'string', line 120, column 6 to column 62)",
  " (in 'string', line 119, column 11 to line 121, column 5)",
  " (in 'string', line 117, column 8 to column 64)",
  " (in 'string', line 116, column 13 to line 118, column 7)",
  " (in 'string', line 114, column 8 to column 75)",
  " (in 'string', line 115, column 8 to column 45)",
  " (in 'string', line 112, column 32 to line 116, column 7)",
  " (in 'string', line 112, column 6 to line 118, column 7)",
  " (in 'string', line 111, column 17 to line 119, column 5)",
  " (in 'string', line 111, column 4 to line 121, column 5)",
  " (in 'string', line 103, column 19 to line 122, column 3)",
  " (in 'string', line 103, column 2 to line 122, column 3)",
  " (in 'string', line 67, column 13 to column 18)",
  " (in 'string', line 67, column 2 to column 20)",
  " (in 'string', line 68, column 2 to column 17)",
  " (in 'string', line 71, column 4 to column 35)",
  " (in 'string', line 72, column 4 to column 35)",
  " (in 'string', line 73, column 4 to column 20)",
  " (in 'string', line 75, column 6 to column 36)",
  " (in 'string', line 74, column 23 to line 76, column 5)",
  " (in 'string', line 74, column 4 to line 76, column 5)",
  " (in 'string', line 80, column 8 to column 75)",
  " (in 'string', line 78, column 32 to line 81, column 7)",
  " (in 'string', line 78, column 6 to line 81, column 7)",
  " (in 'string', line 77, column 17 to line 82, column 5)",
  " (in 'string', line 77, column 4 to line 82, column 5)",
  " (in 'string', line 69, column 19 to line 83, column 3)",
  " (in 'string', line 69, column 2 to line 83, column 3)",
  " (in 'string', line 85, column 2 to column 44)",
  " (in 'string', line 88, column 2 to column 48)",
  " (in 'string', line 89, column 2 to column 61)",
  " (in 'string', line 90, column 2 to column 61)",
  " (in 'string', line 92, column 2 to column 35)",
  " (in 'string', line 93, column 2 to column 33)",
  " (in 'string', line 94, column 2 to column 35)",
  " (in 'string', line 95, column 2 to column 33)",
  " (in 'string', line 97, column 2 to column 35)",
  " (in 'string', line 41, column 2 to column 17)",
  " (in 'string', line 42, column 2 to column 12)",
  " (in 'string', line 43, column 2 to column 12)",
  " (in 'string', line 44, column 13 to column 18)",
  " (in 'string', line 44, column 2 to column 20)",
  " (in 'string', line 45, column 16 to column 21)",
  " (in 'string', line 45, column 2 to column 23)",
  " (in 'string', line 46, column 12 to column 17)",
  " (in 'string', line 46, column 2 to column 19)",
  " (in 'string', line 47, column 13 to column 18)",
  " (in 'string', line 47, column 2 to column 20)",
  " (in 'string', line 48, column 2 to column 13)",
  " (in 'string', line 49, column 15 to column 20)",
  " (in 'string', line 49, column 2 to column 22)",
  " (in 'string', line 54, column 24 to column 29)",
  " (in 'string', line 55, column 26 to column 31)",
  " (in 'string', line 56, column 26 to column 31)",
  " (in 'string', line 100, column 13 to column 18)",
  " (in 'string', line 101, column 17 to column 22)",
  " (in 'string', line 6, column 4 to column 48)",
  " (in 'string', line 5, column 30 to line 7, column 3)",
  " (in 'string', line 9, column 4 to column 12)",
  " (in 'string', line 10, column 4 to column 12)",
  " (in 'string', line 11, column 4 to column 12)",
  " (in 'string', line 12, column 4 to column 12)",
  " (in 'string', line 13, column 4 to column 15)",
  " (in 'string', line 14, column 4 to column 21)",
  " (in 'string', line 15, column 4 to column 37)",
  " (in 'string', line 16, column 4 to column 37)",
  " (in 'string', line 17, column 4 to column 33)",
  " (in 'string', line 18, column 4 to column 67)",
  " (in 'string', line 19, column 4 to column 17)",
  " (in 'string', line 8, column 51 to line 20, column 3)",
  " (in 'string', line 22, column 4 to column 14)",
  " (in 'string', line 23, column 4 to column 18)",
  " (in 'string', line 24, column 4 to column 15)",
  " (in 'string', line 25, column 4 to column 24)",
  " (in 'string', line 26, column 4 to column 17)",
  " (in 'string', line 27, column 4 to column 14)",
  " (in 'string', line 30, column 6 to column 59)",
  " (in 'string', line 32, column 6 to column 52)",
  " (in 'string', line 34, column 6 to column 43)",
  " (in 'string', line 28, column 30 to line 35, column 5)",
  " (in 'string', line 28, column 4 to line 35, column 5)",
  " (in 'string', line 36, column 4 to column 17)",
  " (in 'string', line 21, column 62 to line 37, column 3)"};
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>* = nullptr>
stan::promote_args_t<T0__, stan::base_type_t<T1__>>
DE(const T0__& y, const T1__& pars_arg__, std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_stan_scalar<T2__>>* = nullptr>
stan::promote_args_t<T0__, stan::base_type_t<T1__>, T2__>
rk4_step(const T0__& y, const T1__& pars_arg__, const T2__& interval,
         std::ostream* pstream__);
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>* = nullptr>
stan::promote_args_t<T0__, stan::base_type_t<T1__>, T2__, T3__>
rk4(const T0__& y, const T1__& pars_arg__, const T2__& interval, const T3__&
    step_size, std::ostream* pstream__);
template <typename T0__, typename T1__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>>*>
stan::promote_args_t<T0__, stan::base_type_t<T1__>>
DE(const T0__& y, const T1__& pars_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
                             stan::base_type_t<T1__>>;
  int current_statement__ = 0;
  const auto& pars = stan::math::to_ref(pars_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    current_statement__ = 74;
    return (stan::model::rvalue(pars, "pars", stan::model::index_uni(1)) *
           stan::math::pow((y /
             stan::model::rvalue(pars, "pars", stan::model::index_uni(3))),
             -stan::model::rvalue(pars, "pars", stan::model::index_uni(2))));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T2__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_stan_scalar<T2__>>*>
stan::promote_args_t<T0__, stan::base_type_t<T1__>, T2__>
rk4_step(const T0__& y, const T1__& pars_arg__, const T2__& interval,
         std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
                             stan::base_type_t<T1__>, T2__>;
  int current_statement__ = 0;
  const auto& pars = stan::math::to_ref(pars_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ k1 = DUMMY_VAR__;
    local_scalar_t__ k2 = DUMMY_VAR__;
    local_scalar_t__ k3 = DUMMY_VAR__;
    local_scalar_t__ k4 = DUMMY_VAR__;
    local_scalar_t__ y_hat = DUMMY_VAR__;
    current_statement__ = 81;
    k1 = DE(y, pars, pstream__);
    current_statement__ = 82;
    k2 = DE((y + ((interval * k1) / 2.0)), pars, pstream__);
    current_statement__ = 83;
    k3 = DE((y + ((interval * k2) / 2.0)), pars, pstream__);
    current_statement__ = 84;
    k4 = DE((y + (interval * k3)), pars, pstream__);
    current_statement__ = 85;
    y_hat = (y + (((1.0 / 6.0) * (((k1 + (2.0 * k2)) + (2.0 * k3)) + k4)) *
      interval));
    current_statement__ = 86;
    return y_hat;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
template <typename T0__, typename T1__, typename T2__, typename T3__,
          stan::require_all_t<stan::is_stan_scalar<T0__>,
                              stan::is_col_vector<T1__>,
                              stan::is_vt_not_complex<T1__>,
                              stan::is_stan_scalar<T2__>,
                              stan::is_stan_scalar<T3__>>*>
stan::promote_args_t<T0__, stan::base_type_t<T1__>, T2__, T3__>
rk4(const T0__& y, const T1__& pars_arg__, const T2__& interval, const T3__&
    step_size, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
                             stan::base_type_t<T1__>, T2__, T3__>;
  int current_statement__ = 0;
  const auto& pars = stan::math::to_ref(pars_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    int steps = std::numeric_limits<int>::min();
    local_scalar_t__ duration = DUMMY_VAR__;
    local_scalar_t__ y_hat = DUMMY_VAR__;
    local_scalar_t__ step_size_temp = DUMMY_VAR__;
    current_statement__ = 92;
    duration = 0;
    current_statement__ = 93;
    y_hat = y;
    current_statement__ = 98;
    while (stan::math::logical_lt(duration, interval)) {
      current_statement__ = 94;
      step_size_temp = stan::math::min(
                         (Eigen::Matrix<local_scalar_t__,1,-1>(2) <<
                                                                    step_size,
                                                                    (interval
                                                                    -
                                                                    duration)).finished());
      current_statement__ = 95;
      y_hat = rk4_step(y_hat, pars, step_size_temp, pstream__);
      current_statement__ = 96;
      duration = (duration + step_size_temp);
    }
    current_statement__ = 99;
    return y_hat;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_power_multi_ind final : public model_base_crtp<model_power_multi_ind> {
private:
  double step_size;
  int n_obs;
  int n_ind;
  std::vector<double> y_obs;
  std::vector<int> obs_index;
  std::vector<double> time;
  std::vector<int> ind_id;
  double y_bar;
  std::vector<double> y_0_obs;
public:
  ~model_power_multi_ind() {}
  model_power_multi_ind(stan::io::var_context& context__, unsigned int
                        random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_power_multi_ind_namespace::model_power_multi_ind";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 55;
      context__.validate_dims("data initialization", "step_size", "double",
        std::vector<size_t>{});
      step_size = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 55;
      step_size = context__.vals_r("step_size")[(1 - 1)];
      current_statement__ = 56;
      context__.validate_dims("data initialization", "n_obs", "int",
        std::vector<size_t>{});
      n_obs = std::numeric_limits<int>::min();
      current_statement__ = 56;
      n_obs = context__.vals_i("n_obs")[(1 - 1)];
      current_statement__ = 57;
      context__.validate_dims("data initialization", "n_ind", "int",
        std::vector<size_t>{});
      n_ind = std::numeric_limits<int>::min();
      current_statement__ = 57;
      n_ind = context__.vals_i("n_ind")[(1 - 1)];
      current_statement__ = 58;
      stan::math::validate_non_negative_index("y_obs", "n_obs", n_obs);
      current_statement__ = 59;
      context__.validate_dims("data initialization", "y_obs", "double",
        std::vector<size_t>{static_cast<size_t>(n_obs)});
      y_obs = std::vector<double>(n_obs,
                std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 59;
      y_obs = context__.vals_r("y_obs");
      current_statement__ = 60;
      stan::math::validate_non_negative_index("obs_index", "n_obs", n_obs);
      current_statement__ = 61;
      context__.validate_dims("data initialization", "obs_index", "int",
        std::vector<size_t>{static_cast<size_t>(n_obs)});
      obs_index = std::vector<int>(n_obs, std::numeric_limits<int>::min());
      current_statement__ = 61;
      obs_index = context__.vals_i("obs_index");
      current_statement__ = 62;
      stan::math::validate_non_negative_index("time", "n_obs", n_obs);
      current_statement__ = 63;
      context__.validate_dims("data initialization", "time", "double",
        std::vector<size_t>{static_cast<size_t>(n_obs)});
      time = std::vector<double>(n_obs,
               std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 63;
      time = context__.vals_r("time");
      current_statement__ = 64;
      stan::math::validate_non_negative_index("ind_id", "n_obs", n_obs);
      current_statement__ = 65;
      context__.validate_dims("data initialization", "ind_id", "int",
        std::vector<size_t>{static_cast<size_t>(n_obs)});
      ind_id = std::vector<int>(n_obs, std::numeric_limits<int>::min());
      current_statement__ = 65;
      ind_id = context__.vals_i("ind_id");
      current_statement__ = 66;
      context__.validate_dims("data initialization", "y_bar", "double",
        std::vector<size_t>{});
      y_bar = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 66;
      y_bar = context__.vals_r("y_bar")[(1 - 1)];
      current_statement__ = 67;
      stan::math::validate_non_negative_index("y_0_obs", "n_ind", n_ind);
      current_statement__ = 68;
      context__.validate_dims("data initialization", "y_0_obs", "double",
        std::vector<size_t>{static_cast<size_t>(n_ind)});
      y_0_obs = std::vector<double>(n_ind,
                  std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 68;
      y_0_obs = context__.vals_r("y_0_obs");
      current_statement__ = 69;
      stan::math::validate_non_negative_index("ind_y_0", "n_ind", n_ind);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("ind_coeff", "n_ind", n_ind);
      current_statement__ = 71;
      stan::math::validate_non_negative_index("ind_power", "n_ind", n_ind);
      current_statement__ = 72;
      stan::math::validate_non_negative_index("y_hat", "n_obs", n_obs);
      current_statement__ = 73;
      stan::math::validate_non_negative_index("Delta_hat", "n_obs", n_obs);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = n_ind + n_ind + n_ind + 1 + 1 + 1 + 1 + 1;
  }
  inline std::string model_name() const final {
    return "model_power_multi_ind";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_power_multi_ind_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<local_scalar_t__> ind_y_0 =
        std::vector<local_scalar_t__>(n_ind, DUMMY_VAR__);
      current_statement__ = 1;
      ind_y_0 = in__.template read_constrain_lb<
                  std::vector<local_scalar_t__>, jacobian__>(0, lp__, n_ind);
      std::vector<local_scalar_t__> ind_coeff =
        std::vector<local_scalar_t__>(n_ind, DUMMY_VAR__);
      current_statement__ = 2;
      ind_coeff = in__.template read_constrain_lb<
                    std::vector<local_scalar_t__>, jacobian__>(0, lp__,
                    n_ind);
      std::vector<local_scalar_t__> ind_power =
        std::vector<local_scalar_t__>(n_ind, DUMMY_VAR__);
      current_statement__ = 3;
      ind_power = in__.template read_constrain_lb<
                    std::vector<local_scalar_t__>, jacobian__>(0, lp__,
                    n_ind);
      local_scalar_t__ species_coeff_mean = DUMMY_VAR__;
      current_statement__ = 4;
      species_coeff_mean = in__.template read<local_scalar_t__>();
      local_scalar_t__ species_coeff_sd = DUMMY_VAR__;
      current_statement__ = 5;
      species_coeff_sd = in__.template read_constrain_lb<local_scalar_t__,
                           jacobian__>(0, lp__);
      local_scalar_t__ species_power_mean = DUMMY_VAR__;
      current_statement__ = 6;
      species_power_mean = in__.template read<local_scalar_t__>();
      local_scalar_t__ species_power_sd = DUMMY_VAR__;
      current_statement__ = 7;
      species_power_sd = in__.template read_constrain_lb<local_scalar_t__,
                           jacobian__>(0, lp__);
      local_scalar_t__ global_error_sigma = DUMMY_VAR__;
      current_statement__ = 8;
      global_error_sigma = in__.template read_constrain_lb<local_scalar_t__,
                             jacobian__>(0, lp__);
      {
        current_statement__ = 30;
        stan::math::validate_non_negative_index("y_hat", "n_obs", n_obs);
        std::vector<local_scalar_t__> y_hat =
          std::vector<local_scalar_t__>(n_obs, DUMMY_VAR__);
        Eigen::Matrix<local_scalar_t__,-1,1> pars =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(3, DUMMY_VAR__);
        current_statement__ = 45;
        for (int i = 1; i <= n_obs; ++i) {
          current_statement__ = 33;
          stan::model::assign(pars,
            stan::model::rvalue(ind_coeff, "ind_coeff",
              stan::model::index_uni(
                stan::model::rvalue(ind_id, "ind_id",
                  stan::model::index_uni(i)))), "assigning variable pars",
            stan::model::index_uni(1));
          current_statement__ = 34;
          stan::model::assign(pars,
            stan::model::rvalue(ind_power, "ind_power",
              stan::model::index_uni(
                stan::model::rvalue(ind_id, "ind_id",
                  stan::model::index_uni(i)))), "assigning variable pars",
            stan::model::index_uni(2));
          current_statement__ = 35;
          stan::model::assign(pars, y_bar, "assigning variable pars",
            stan::model::index_uni(3));
          current_statement__ = 38;
          if (stan::math::logical_eq(
                stan::model::rvalue(obs_index, "obs_index",
                  stan::model::index_uni(i)), 1)) {
            current_statement__ = 36;
            stan::model::assign(y_hat,
              stan::model::rvalue(ind_y_0, "ind_y_0",
                stan::model::index_uni(
                  stan::model::rvalue(ind_id, "ind_id",
                    stan::model::index_uni(i)))), "assigning variable y_hat",
              stan::model::index_uni(i));
          }
          current_statement__ = 43;
          if (stan::math::logical_lt(i, n_obs)) {
            current_statement__ = 41;
            if (stan::math::logical_eq(
                  stan::model::rvalue(ind_id, "ind_id",
                    stan::model::index_uni((i + 1))),
                  stan::model::rvalue(ind_id, "ind_id",
                    stan::model::index_uni(i)))) {
              current_statement__ = 39;
              stan::model::assign(y_hat,
                rk4(
                  stan::model::rvalue(y_hat, "y_hat",
                    stan::model::index_uni(i)), pars,
                  (stan::model::rvalue(time, "time",
                     stan::model::index_uni((i + 1))) -
                  stan::model::rvalue(time, "time", stan::model::index_uni(i))),
                  step_size, pstream__), "assigning variable y_hat",
                stan::model::index_uni((i + 1)));
            }
          }
        }
        current_statement__ = 46;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(y_obs, y_hat,
                         global_error_sigma));
        current_statement__ = 47;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(ind_y_0, y_0_obs,
                         global_error_sigma));
        current_statement__ = 48;
        lp_accum__.add(stan::math::lognormal_lpdf<propto__>(ind_coeff,
                         species_coeff_mean, species_coeff_sd));
        current_statement__ = 49;
        lp_accum__.add(stan::math::lognormal_lpdf<propto__>(ind_power,
                         species_power_mean, species_power_sd));
        current_statement__ = 50;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(species_coeff_mean,
                         0, 2));
        current_statement__ = 51;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(species_coeff_sd, 0,
                         2));
        current_statement__ = 52;
        lp_accum__.add(stan::math::normal_lpdf<propto__>(species_power_mean,
                         0, 2));
        current_statement__ = 53;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(species_power_sd, 0,
                         2));
        current_statement__ = 54;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(global_error_sigma,
                         0, 5));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_power_multi_ind_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<double> ind_y_0 =
        std::vector<double>(n_ind, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      ind_y_0 = in__.template read_constrain_lb<
                  std::vector<local_scalar_t__>, jacobian__>(0, lp__, n_ind);
      std::vector<double> ind_coeff =
        std::vector<double>(n_ind, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      ind_coeff = in__.template read_constrain_lb<
                    std::vector<local_scalar_t__>, jacobian__>(0, lp__,
                    n_ind);
      std::vector<double> ind_power =
        std::vector<double>(n_ind, std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      ind_power = in__.template read_constrain_lb<
                    std::vector<local_scalar_t__>, jacobian__>(0, lp__,
                    n_ind);
      double species_coeff_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 4;
      species_coeff_mean = in__.template read<local_scalar_t__>();
      double species_coeff_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      species_coeff_sd = in__.template read_constrain_lb<local_scalar_t__,
                           jacobian__>(0, lp__);
      double species_power_mean = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      species_power_mean = in__.template read<local_scalar_t__>();
      double species_power_sd = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      species_power_sd = in__.template read_constrain_lb<local_scalar_t__,
                           jacobian__>(0, lp__);
      double global_error_sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 8;
      global_error_sigma = in__.template read_constrain_lb<local_scalar_t__,
                             jacobian__>(0, lp__);
      out__.write(ind_y_0);
      out__.write(ind_coeff);
      out__.write(ind_power);
      out__.write(species_coeff_mean);
      out__.write(species_coeff_sd);
      out__.write(species_power_mean);
      out__.write(species_power_sd);
      out__.write(global_error_sigma);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      std::vector<double> y_hat =
        std::vector<double>(n_obs, std::numeric_limits<double>::quiet_NaN());
      std::vector<double> Delta_hat =
        std::vector<double>(n_obs, std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> pars =
        Eigen::Matrix<double,-1,1>::Constant(3,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 29;
      for (int i = 1; i <= n_obs; ++i) {
        current_statement__ = 12;
        stan::model::assign(pars,
          stan::model::rvalue(ind_coeff, "ind_coeff",
            stan::model::index_uni(
              stan::model::rvalue(ind_id, "ind_id", stan::model::index_uni(i)))),
          "assigning variable pars", stan::model::index_uni(1));
        current_statement__ = 13;
        stan::model::assign(pars,
          stan::model::rvalue(ind_power, "ind_power",
            stan::model::index_uni(
              stan::model::rvalue(ind_id, "ind_id", stan::model::index_uni(i)))),
          "assigning variable pars", stan::model::index_uni(2));
        current_statement__ = 14;
        stan::model::assign(pars, y_bar, "assigning variable pars",
          stan::model::index_uni(3));
        current_statement__ = 17;
        if (stan::math::logical_eq(
              stan::model::rvalue(obs_index, "obs_index",
                stan::model::index_uni(i)), 1)) {
          current_statement__ = 15;
          stan::model::assign(y_hat,
            stan::model::rvalue(ind_y_0, "ind_y_0",
              stan::model::index_uni(
                stan::model::rvalue(ind_id, "ind_id",
                  stan::model::index_uni(i)))), "assigning variable y_hat",
            stan::model::index_uni(i));
        }
        current_statement__ = 27;
        if (stan::math::logical_lt(i, n_obs)) {
          current_statement__ = 25;
          if (stan::math::logical_eq(
                stan::model::rvalue(ind_id, "ind_id",
                  stan::model::index_uni((i + 1))),
                stan::model::rvalue(ind_id, "ind_id",
                  stan::model::index_uni(i)))) {
            current_statement__ = 22;
            stan::model::assign(y_hat,
              rk4(
                stan::model::rvalue(y_hat, "y_hat", stan::model::index_uni(i)),
                pars,
                (stan::model::rvalue(time, "time",
                   stan::model::index_uni((i + 1))) -
                stan::model::rvalue(time, "time", stan::model::index_uni(i))),
                step_size, pstream__), "assigning variable y_hat",
              stan::model::index_uni((i + 1)));
            current_statement__ = 23;
            stan::model::assign(Delta_hat,
              (stan::model::rvalue(y_hat, "y_hat",
                 stan::model::index_uni((i + 1))) -
              stan::model::rvalue(y_hat, "y_hat", stan::model::index_uni(i))),
              "assigning variable Delta_hat", stan::model::index_uni(i));
          } else {
            current_statement__ = 20;
            stan::model::assign(Delta_hat,
              (DE(
                 stan::model::rvalue(y_hat, "y_hat",
                   stan::model::index_uni(i)), pars, pstream__) *
              (stan::model::rvalue(time, "time", stan::model::index_uni(i)) -
              stan::model::rvalue(time, "time",
                stan::model::index_uni((i - 1))))),
              "assigning variable Delta_hat", stan::model::index_uni(i));
          }
        } else {
          current_statement__ = 18;
          stan::model::assign(Delta_hat,
            (DE(
               stan::model::rvalue(y_hat, "y_hat", stan::model::index_uni(i)),
               pars, pstream__) *
            (stan::model::rvalue(time, "time", stan::model::index_uni(i)) -
            stan::model::rvalue(time, "time", stan::model::index_uni((i - 1))))),
            "assigning variable Delta_hat", stan::model::index_uni(i));
        }
      }
      out__.write(y_hat);
      out__.write(Delta_hat);
      out__.write(pars);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<local_scalar_t__> ind_y_0 =
        std::vector<local_scalar_t__>(n_ind, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(ind_y_0,
        in__.read<std::vector<local_scalar_t__>>(n_ind),
        "assigning variable ind_y_0");
      out__.write_free_lb(0, ind_y_0);
      std::vector<local_scalar_t__> ind_coeff =
        std::vector<local_scalar_t__>(n_ind, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(ind_coeff,
        in__.read<std::vector<local_scalar_t__>>(n_ind),
        "assigning variable ind_coeff");
      out__.write_free_lb(0, ind_coeff);
      std::vector<local_scalar_t__> ind_power =
        std::vector<local_scalar_t__>(n_ind, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(ind_power,
        in__.read<std::vector<local_scalar_t__>>(n_ind),
        "assigning variable ind_power");
      out__.write_free_lb(0, ind_power);
      local_scalar_t__ species_coeff_mean = DUMMY_VAR__;
      current_statement__ = 4;
      species_coeff_mean = in__.read<local_scalar_t__>();
      out__.write(species_coeff_mean);
      local_scalar_t__ species_coeff_sd = DUMMY_VAR__;
      current_statement__ = 5;
      species_coeff_sd = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, species_coeff_sd);
      local_scalar_t__ species_power_mean = DUMMY_VAR__;
      current_statement__ = 6;
      species_power_mean = in__.read<local_scalar_t__>();
      out__.write(species_power_mean);
      local_scalar_t__ species_power_sd = DUMMY_VAR__;
      current_statement__ = 7;
      species_power_sd = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, species_power_sd);
      local_scalar_t__ global_error_sigma = DUMMY_VAR__;
      current_statement__ = 8;
      global_error_sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, global_error_sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "ind_y_0",
        "double", std::vector<size_t>{static_cast<size_t>(n_ind)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "ind_coeff",
        "double", std::vector<size_t>{static_cast<size_t>(n_ind)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "ind_power",
        "double", std::vector<size_t>{static_cast<size_t>(n_ind)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization",
        "species_coeff_mean", "double", std::vector<size_t>{});
      current_statement__ = 5;
      context__.validate_dims("parameter initialization", "species_coeff_sd",
        "double", std::vector<size_t>{});
      current_statement__ = 6;
      context__.validate_dims("parameter initialization",
        "species_power_mean", "double", std::vector<size_t>{});
      current_statement__ = 7;
      context__.validate_dims("parameter initialization", "species_power_sd",
        "double", std::vector<size_t>{});
      current_statement__ = 8;
      context__.validate_dims("parameter initialization",
        "global_error_sigma", "double", std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<local_scalar_t__> ind_y_0 =
        std::vector<local_scalar_t__>(n_ind, DUMMY_VAR__);
      current_statement__ = 1;
      ind_y_0 = context__.vals_r("ind_y_0");
      out__.write_free_lb(0, ind_y_0);
      std::vector<local_scalar_t__> ind_coeff =
        std::vector<local_scalar_t__>(n_ind, DUMMY_VAR__);
      current_statement__ = 2;
      ind_coeff = context__.vals_r("ind_coeff");
      out__.write_free_lb(0, ind_coeff);
      std::vector<local_scalar_t__> ind_power =
        std::vector<local_scalar_t__>(n_ind, DUMMY_VAR__);
      current_statement__ = 3;
      ind_power = context__.vals_r("ind_power");
      out__.write_free_lb(0, ind_power);
      local_scalar_t__ species_coeff_mean = DUMMY_VAR__;
      current_statement__ = 4;
      species_coeff_mean = context__.vals_r("species_coeff_mean")[(1 - 1)];
      out__.write(species_coeff_mean);
      local_scalar_t__ species_coeff_sd = DUMMY_VAR__;
      current_statement__ = 5;
      species_coeff_sd = context__.vals_r("species_coeff_sd")[(1 - 1)];
      out__.write_free_lb(0, species_coeff_sd);
      local_scalar_t__ species_power_mean = DUMMY_VAR__;
      current_statement__ = 6;
      species_power_mean = context__.vals_r("species_power_mean")[(1 - 1)];
      out__.write(species_power_mean);
      local_scalar_t__ species_power_sd = DUMMY_VAR__;
      current_statement__ = 7;
      species_power_sd = context__.vals_r("species_power_sd")[(1 - 1)];
      out__.write_free_lb(0, species_power_sd);
      local_scalar_t__ global_error_sigma = DUMMY_VAR__;
      current_statement__ = 8;
      global_error_sigma = context__.vals_r("global_error_sigma")[(1 - 1)];
      out__.write_free_lb(0, global_error_sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"ind_y_0", "ind_coeff", "ind_power",
                "species_coeff_mean", "species_coeff_sd",
                "species_power_mean", "species_power_sd",
                "global_error_sigma"};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"y_hat", "Delta_hat", "pars"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    n_ind)},
                std::vector<size_t>{static_cast<size_t>(n_ind)},
                std::vector<size_t>{static_cast<size_t>(n_ind)},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}, std::vector<size_t>{},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(n_obs)},
             std::vector<size_t>{static_cast<size_t>(n_obs)},
             std::vector<size_t>{static_cast<size_t>(3)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
      param_names__.emplace_back(std::string() + "ind_y_0" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
      param_names__.emplace_back(std::string() + "ind_coeff" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
      param_names__.emplace_back(std::string() + "ind_power" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "species_coeff_mean");
    param_names__.emplace_back(std::string() + "species_coeff_sd");
    param_names__.emplace_back(std::string() + "species_power_mean");
    param_names__.emplace_back(std::string() + "species_power_sd");
    param_names__.emplace_back(std::string() + "global_error_sigma");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_hat" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "Delta_hat" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        param_names__.emplace_back(std::string() + "pars" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
      param_names__.emplace_back(std::string() + "ind_y_0" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
      param_names__.emplace_back(std::string() + "ind_coeff" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
      param_names__.emplace_back(std::string() + "ind_power" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "species_coeff_mean");
    param_names__.emplace_back(std::string() + "species_coeff_sd");
    param_names__.emplace_back(std::string() + "species_power_mean");
    param_names__.emplace_back(std::string() + "species_power_sd");
    param_names__.emplace_back(std::string() + "global_error_sigma");
    if (emit_transformed_parameters__) {}
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "y_hat" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        param_names__.emplace_back(std::string() + "Delta_hat" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= 3; ++sym1__) {
        param_names__.emplace_back(std::string() + "pars" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"ind_y_0\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_ind) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"ind_coeff\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_ind) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"ind_power\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_ind) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"species_coeff_mean\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"species_coeff_sd\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"species_power_mean\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"species_power_sd\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"global_error_sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_hat\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_obs) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"Delta_hat\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_obs) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"pars\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(3) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"ind_y_0\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_ind) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"ind_coeff\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_ind) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"ind_power\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_ind) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"species_coeff_mean\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"species_coeff_sd\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"species_power_mean\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"species_power_sd\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"global_error_sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_hat\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_obs) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"Delta_hat\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(n_obs) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"pars\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(3) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((n_ind + n_ind) + n_ind) + 1) + 1) + 1)
      + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (((n_obs +
      n_obs) + 3));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (((((((n_ind + n_ind) + n_ind) + 1) + 1) + 1)
      + 1) + 1);
    const size_t num_transformed = emit_transformed_parameters * (0);
    const size_t num_gen_quantities = emit_generated_quantities * (((n_obs +
      n_obs) + 3));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_power_multi_ind_namespace::model_power_multi_ind;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_power_multi_ind_namespace::profiles__;
}
#endif
#endif
