// Generated by rstantools.  Do not edit by hand.

/*
    rmot is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    rmot is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with rmot.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1-4-gd72b68b7-dirty
#include <stan/model/model_header.hpp>
namespace model_power_multi_ind_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'power_multi_ind', line 54, column 2 to column 31)",
                                                      " (in 'power_multi_ind', line 55, column 2 to column 33)",
                                                      " (in 'power_multi_ind', line 56, column 2 to column 33)",
                                                      " (in 'power_multi_ind', line 58, column 2 to column 26)",
                                                      " (in 'power_multi_ind', line 59, column 2 to column 33)",
                                                      " (in 'power_multi_ind', line 60, column 2 to column 26)",
                                                      " (in 'power_multi_ind', line 61, column 2 to column 33)",
                                                      " (in 'power_multi_ind', line 63, column 2 to column 35)",
                                                      " (in 'power_multi_ind', line 99, column 2 to column 20)",
                                                      " (in 'power_multi_ind', line 100, column 2 to column 24)",
                                                      " (in 'power_multi_ind', line 101, column 2 to column 17)",
                                                      " (in 'power_multi_ind', line 104, column 4 to column 35)",
                                                      " (in 'power_multi_ind', line 105, column 4 to column 35)",
                                                      " (in 'power_multi_ind', line 107, column 6 to column 36)",
                                                      " (in 'power_multi_ind', line 106, column 23 to line 108, column 5)",
                                                      " (in 'power_multi_ind', line 106, column 4 to line 108, column 5)",
                                                      " (in 'power_multi_ind', line 118, column 6 to column 80)",
                                                      " (in 'power_multi_ind', line 117, column 11 to line 119, column 5)",
                                                      " (in 'power_multi_ind', line 115, column 8 to column 82)",
                                                      " (in 'power_multi_ind', line 114, column 13 to line 116, column 7)",
                                                      " (in 'power_multi_ind', line 112, column 8 to column 93)",
                                                      " (in 'power_multi_ind', line 113, column 8 to column 45)",
                                                      " (in 'power_multi_ind', line 110, column 32 to line 114, column 7)",
                                                      " (in 'power_multi_ind', line 110, column 6 to line 116, column 7)",
                                                      " (in 'power_multi_ind', line 109, column 17 to line 117, column 5)",
                                                      " (in 'power_multi_ind', line 109, column 4 to line 119, column 5)",
                                                      " (in 'power_multi_ind', line 102, column 19 to line 120, column 3)",
                                                      " (in 'power_multi_ind', line 102, column 2 to line 120, column 3)",
                                                      " (in 'power_multi_ind', line 67, column 13 to column 18)",
                                                      " (in 'power_multi_ind', line 67, column 2 to column 20)",
                                                      " (in 'power_multi_ind', line 68, column 2 to column 17)",
                                                      " (in 'power_multi_ind', line 71, column 4 to column 35)",
                                                      " (in 'power_multi_ind', line 72, column 4 to column 35)",
                                                      " (in 'power_multi_ind', line 74, column 6 to column 36)",
                                                      " (in 'power_multi_ind', line 73, column 23 to line 75, column 5)",
                                                      " (in 'power_multi_ind', line 73, column 4 to line 75, column 5)",
                                                      " (in 'power_multi_ind', line 79, column 8 to column 93)",
                                                      " (in 'power_multi_ind', line 77, column 32 to line 80, column 7)",
                                                      " (in 'power_multi_ind', line 77, column 6 to line 80, column 7)",
                                                      " (in 'power_multi_ind', line 76, column 17 to line 81, column 5)",
                                                      " (in 'power_multi_ind', line 76, column 4 to line 81, column 5)",
                                                      " (in 'power_multi_ind', line 69, column 19 to line 82, column 3)",
                                                      " (in 'power_multi_ind', line 69, column 2 to line 82, column 3)",
                                                      " (in 'power_multi_ind', line 84, column 2 to column 44)",
                                                      " (in 'power_multi_ind', line 87, column 2 to column 48)",
                                                      " (in 'power_multi_ind', line 88, column 2 to column 61)",
                                                      " (in 'power_multi_ind', line 89, column 2 to column 61)",
                                                      " (in 'power_multi_ind', line 91, column 2 to column 35)",
                                                      " (in 'power_multi_ind', line 92, column 2 to column 33)",
                                                      " (in 'power_multi_ind', line 93, column 2 to column 35)",
                                                      " (in 'power_multi_ind', line 94, column 2 to column 33)",
                                                      " (in 'power_multi_ind', line 96, column 2 to column 35)",
                                                      " (in 'power_multi_ind', line 41, column 2 to column 17)",
                                                      " (in 'power_multi_ind', line 42, column 2 to column 12)",
                                                      " (in 'power_multi_ind', line 43, column 2 to column 12)",
                                                      " (in 'power_multi_ind', line 44, column 13 to column 18)",
                                                      " (in 'power_multi_ind', line 44, column 2 to column 20)",
                                                      " (in 'power_multi_ind', line 45, column 16 to column 21)",
                                                      " (in 'power_multi_ind', line 45, column 2 to column 23)",
                                                      " (in 'power_multi_ind', line 46, column 12 to column 17)",
                                                      " (in 'power_multi_ind', line 46, column 2 to column 19)",
                                                      " (in 'power_multi_ind', line 47, column 13 to column 18)",
                                                      " (in 'power_multi_ind', line 47, column 2 to column 20)",
                                                      " (in 'power_multi_ind', line 48, column 13 to column 18)",
                                                      " (in 'power_multi_ind', line 48, column 2 to column 20)",
                                                      " (in 'power_multi_ind', line 49, column 15 to column 20)",
                                                      " (in 'power_multi_ind', line 49, column 2 to column 22)",
                                                      " (in 'power_multi_ind', line 54, column 24 to column 29)",
                                                      " (in 'power_multi_ind', line 55, column 26 to column 31)",
                                                      " (in 'power_multi_ind', line 56, column 26 to column 31)",
                                                      " (in 'power_multi_ind', line 99, column 13 to column 18)",
                                                      " (in 'power_multi_ind', line 100, column 17 to column 22)",
                                                      " (in 'power_multi_ind', line 6, column 4 to column 46)",
                                                      " (in 'power_multi_ind', line 5, column 42 to line 7, column 3)",
                                                      " (in 'power_multi_ind', line 9, column 4 to column 12)",
                                                      " (in 'power_multi_ind', line 10, column 4 to column 12)",
                                                      " (in 'power_multi_ind', line 11, column 4 to column 12)",
                                                      " (in 'power_multi_ind', line 12, column 4 to column 12)",
                                                      " (in 'power_multi_ind', line 13, column 4 to column 15)",
                                                      " (in 'power_multi_ind', line 14, column 4 to column 28)",
                                                      " (in 'power_multi_ind', line 15, column 4 to column 44)",
                                                      " (in 'power_multi_ind', line 16, column 4 to column 44)",
                                                      " (in 'power_multi_ind', line 17, column 4 to column 40)",
                                                      " (in 'power_multi_ind', line 18, column 4 to column 67)",
                                                      " (in 'power_multi_ind', line 19, column 4 to column 17)",
                                                      " (in 'power_multi_ind', line 8, column 63 to line 20, column 3)",
                                                      " (in 'power_multi_ind', line 22, column 4 to column 14)",
                                                      " (in 'power_multi_ind', line 23, column 4 to column 18)",
                                                      " (in 'power_multi_ind', line 24, column 4 to column 15)",
                                                      " (in 'power_multi_ind', line 25, column 4 to column 24)",
                                                      " (in 'power_multi_ind', line 26, column 4 to column 17)",
                                                      " (in 'power_multi_ind', line 27, column 4 to column 14)",
                                                      " (in 'power_multi_ind', line 30, column 6 to column 59)",
                                                      " (in 'power_multi_ind', line 32, column 6 to column 59)",
                                                      " (in 'power_multi_ind', line 34, column 6 to column 43)",
                                                      " (in 'power_multi_ind', line 28, column 30 to line 35, column 5)",
                                                      " (in 'power_multi_ind', line 28, column 4 to line 35, column 5)",
                                                      " (in 'power_multi_ind', line 36, column 4 to column 17)",
                                                      " (in 'power_multi_ind', line 21, column 74 to line 37, column 3)"};
template <typename T0__, typename T1__, typename T2__>
stan::promote_args_t<T0__, T1__,
stan::value_type_t<T2__>>
DE(const T0__& y, const T1__& y_bar, const T2__& pars_arg__,
   std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
          T1__,
          stan::value_type_t<T2__>>;
  const auto& pars = to_ref(pars_arg__);
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    current_statement__ = 73;
    return (pars[(1 - 1)] * pow((y / y_bar), -pars[(2 - 1)]));
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct DE_functor__ {
template <typename T0__, typename T1__, typename T2__>
stan::promote_args_t<T0__, T1__,
stan::value_type_t<T2__>>
operator()(const T0__& y, const T1__& y_bar, const T2__& pars,
           std::ostream* pstream__)  const 
{
return DE(y, y_bar, pars, pstream__);
}
};
template <typename T0__, typename T1__, typename T2__, typename T3__>
stan::promote_args_t<T0__, T1__, stan::value_type_t<T2__>,
T3__>
rk4_step(const T0__& y, const T1__& y_bar, const T2__& pars_arg__,
         const T3__& interval, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
          T1__,
          stan::value_type_t<T2__>,
          T3__>;
  const auto& pars = to_ref(pars_arg__);
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    local_scalar_t__ k1;
    k1 = DUMMY_VAR__;
    
    local_scalar_t__ k2;
    k2 = DUMMY_VAR__;
    
    local_scalar_t__ k3;
    k3 = DUMMY_VAR__;
    
    local_scalar_t__ k4;
    k4 = DUMMY_VAR__;
    
    local_scalar_t__ y_hat;
    y_hat = DUMMY_VAR__;
    
    current_statement__ = 80;
    k1 = DE(y, y_bar, pars, pstream__);
    current_statement__ = 81;
    k2 = DE((y + ((interval * k1) / 2.0)), y_bar, pars, pstream__);
    current_statement__ = 82;
    k3 = DE((y + ((interval * k2) / 2.0)), y_bar, pars, pstream__);
    current_statement__ = 83;
    k4 = DE((y + (interval * k3)), y_bar, pars, pstream__);
    current_statement__ = 84;
    y_hat = (y +
              (((1.0 / 6.0) * (((k1 + (2.0 * k2)) + (2.0 * k3)) + k4)) *
                interval));
    current_statement__ = 85;
    return y_hat;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct rk4_step_functor__ {
template <typename T0__, typename T1__, typename T2__, typename T3__>
stan::promote_args_t<T0__, T1__, stan::value_type_t<T2__>,
T3__>
operator()(const T0__& y, const T1__& y_bar, const T2__& pars,
           const T3__& interval, std::ostream* pstream__)  const 
{
return rk4_step(y, y_bar, pars, interval, pstream__);
}
};
template <typename T0__, typename T1__, typename T2__, typename T3__,
typename T4__>
stan::promote_args_t<T0__, T1__, stan::value_type_t<T2__>, T3__,
T4__>
rk4(const T0__& y, const T1__& y_bar, const T2__& pars_arg__,
    const T3__& interval, const T4__& step_size, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<T0__,
          T1__,
          stan::value_type_t<T2__>,
          T3__,
          T4__>;
  const auto& pars = to_ref(pars_arg__);
  const static bool propto__ = true;
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  (void) DUMMY_VAR__;  // suppress unused var warning
  
  try {
    int steps;
    steps = std::numeric_limits<int>::min();
    
    local_scalar_t__ duration;
    duration = DUMMY_VAR__;
    
    local_scalar_t__ y_hat;
    y_hat = DUMMY_VAR__;
    
    local_scalar_t__ step_size_temp;
    step_size_temp = DUMMY_VAR__;
    
    current_statement__ = 91;
    duration = 0;
    current_statement__ = 92;
    y_hat = y;
    current_statement__ = 97;
    while (logical_lt(duration, interval)) {
      current_statement__ = 93;
      step_size_temp = min((Eigen::Matrix<local_scalar_t__,1,-1>(2) <<
                         step_size, (interval - duration)).finished());
      current_statement__ = 94;
      y_hat = rk4_step(y_hat, y_bar, pars, step_size_temp, pstream__);
      current_statement__ = 95;
      duration = (duration + step_size_temp);
    }
    current_statement__ = 98;
    return y_hat;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
  }
  
}
struct rk4_functor__ {
template <typename T0__, typename T1__, typename T2__, typename T3__,
typename T4__>
stan::promote_args_t<T0__, T1__, stan::value_type_t<T2__>, T3__,
T4__>
operator()(const T0__& y, const T1__& y_bar, const T2__& pars,
           const T3__& interval, const T4__& step_size,
           std::ostream* pstream__)  const 
{
return rk4(y, y_bar, pars, interval, step_size, pstream__);
}
};
#include <stan_meta_header.hpp>
class model_power_multi_ind final : public model_base_crtp<model_power_multi_ind> {
private:
  double step_size;
  int n_obs;
  int n_ind;
  std::vector<double> y_obs;
  std::vector<int> obs_index;
  std::vector<double> time;
  std::vector<int> ind_id;
  std::vector<double> y_bar;
  std::vector<double> y_0_obs;
 
public:
  ~model_power_multi_ind() { }
  
  inline std::string model_name() const final { return "model_power_multi_ind"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1-4-gd72b68b7-dirty", "stancflags = "};
  }
  
  
  model_power_multi_ind(stan::io::var_context& context__,
                        unsigned int random_seed__ = 0,
                        std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_power_multi_ind_namespace::model_power_multi_ind";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 53;
      context__.validate_dims("data initialization","step_size","double",
          context__.to_vec());
      step_size = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 53;
      step_size = context__.vals_r("step_size")[(1 - 1)];
      current_statement__ = 54;
      context__.validate_dims("data initialization","n_obs","int",
          context__.to_vec());
      n_obs = std::numeric_limits<int>::min();
      
      current_statement__ = 54;
      n_obs = context__.vals_i("n_obs")[(1 - 1)];
      current_statement__ = 55;
      context__.validate_dims("data initialization","n_ind","int",
          context__.to_vec());
      n_ind = std::numeric_limits<int>::min();
      
      current_statement__ = 55;
      n_ind = context__.vals_i("n_ind")[(1 - 1)];
      current_statement__ = 56;
      validate_non_negative_index("y_obs", "n_obs", n_obs);
      current_statement__ = 57;
      context__.validate_dims("data initialization","y_obs","double",
          context__.to_vec(n_obs));
      y_obs = std::vector<double>(n_obs, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 57;
      assign(y_obs, nil_index_list(), context__.vals_r("y_obs"),
        "assigning variable y_obs");
      current_statement__ = 58;
      validate_non_negative_index("obs_index", "n_obs", n_obs);
      current_statement__ = 59;
      context__.validate_dims("data initialization","obs_index","int",
          context__.to_vec(n_obs));
      obs_index = std::vector<int>(n_obs, std::numeric_limits<int>::min());
      
      current_statement__ = 59;
      assign(obs_index, nil_index_list(), context__.vals_i("obs_index"),
        "assigning variable obs_index");
      current_statement__ = 60;
      validate_non_negative_index("time", "n_obs", n_obs);
      current_statement__ = 61;
      context__.validate_dims("data initialization","time","double",
          context__.to_vec(n_obs));
      time = std::vector<double>(n_obs, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 61;
      assign(time, nil_index_list(), context__.vals_r("time"),
        "assigning variable time");
      current_statement__ = 62;
      validate_non_negative_index("ind_id", "n_obs", n_obs);
      current_statement__ = 63;
      context__.validate_dims("data initialization","ind_id","int",
          context__.to_vec(n_obs));
      ind_id = std::vector<int>(n_obs, std::numeric_limits<int>::min());
      
      current_statement__ = 63;
      assign(ind_id, nil_index_list(), context__.vals_i("ind_id"),
        "assigning variable ind_id");
      current_statement__ = 64;
      validate_non_negative_index("y_bar", "n_ind", n_ind);
      current_statement__ = 65;
      context__.validate_dims("data initialization","y_bar","double",
          context__.to_vec(n_ind));
      y_bar = std::vector<double>(n_ind, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 65;
      assign(y_bar, nil_index_list(), context__.vals_r("y_bar"),
        "assigning variable y_bar");
      current_statement__ = 66;
      validate_non_negative_index("y_0_obs", "n_ind", n_ind);
      current_statement__ = 67;
      context__.validate_dims("data initialization","y_0_obs","double",
          context__.to_vec(n_ind));
      y_0_obs = std::vector<double>(n_ind, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 67;
      assign(y_0_obs, nil_index_list(), context__.vals_r("y_0_obs"),
        "assigning variable y_0_obs");
      current_statement__ = 68;
      validate_non_negative_index("ind_y_0", "n_ind", n_ind);
      current_statement__ = 69;
      validate_non_negative_index("ind_coeff", "n_ind", n_ind);
      current_statement__ = 70;
      validate_non_negative_index("ind_power", "n_ind", n_ind);
      current_statement__ = 71;
      validate_non_negative_index("y_hat", "n_obs", n_obs);
      current_statement__ = 72;
      validate_non_negative_index("Delta_hat", "n_obs", n_obs);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += n_ind;
      num_params_r__ += n_ind;
      num_params_r__ += n_ind;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_power_multi_ind_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      std::vector<local_scalar_t__> ind_y_0;
      ind_y_0 = std::vector<local_scalar_t__>(n_ind, DUMMY_VAR__);
      
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        current_statement__ = 1;
        assign(ind_y_0, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable ind_y_0");}
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        current_statement__ = 1;
        if (jacobian__) {
          current_statement__ = 1;
          assign(ind_y_0, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(ind_y_0[(sym1__ - 1)], 0, lp__),
            "assigning variable ind_y_0");
        } else {
          current_statement__ = 1;
          assign(ind_y_0, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(ind_y_0[(sym1__ - 1)], 0),
            "assigning variable ind_y_0");
        }}
      std::vector<local_scalar_t__> ind_coeff;
      ind_coeff = std::vector<local_scalar_t__>(n_ind, DUMMY_VAR__);
      
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        current_statement__ = 2;
        assign(ind_coeff, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable ind_coeff");}
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        current_statement__ = 2;
        if (jacobian__) {
          current_statement__ = 2;
          assign(ind_coeff, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(ind_coeff[(sym1__ - 1)], 0, lp__),
            "assigning variable ind_coeff");
        } else {
          current_statement__ = 2;
          assign(ind_coeff, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(ind_coeff[(sym1__ - 1)], 0),
            "assigning variable ind_coeff");
        }}
      std::vector<local_scalar_t__> ind_power;
      ind_power = std::vector<local_scalar_t__>(n_ind, DUMMY_VAR__);
      
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        current_statement__ = 3;
        assign(ind_power, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable ind_power");}
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        current_statement__ = 3;
        if (jacobian__) {
          current_statement__ = 3;
          assign(ind_power, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(ind_power[(sym1__ - 1)], 0, lp__),
            "assigning variable ind_power");
        } else {
          current_statement__ = 3;
          assign(ind_power, cons_list(index_uni(sym1__), nil_index_list()),
            stan::math::lb_constrain(ind_power[(sym1__ - 1)], 0),
            "assigning variable ind_power");
        }}
      local_scalar_t__ species_coeff_mean;
      species_coeff_mean = DUMMY_VAR__;
      
      current_statement__ = 4;
      species_coeff_mean = in__.scalar();
      local_scalar_t__ species_coeff_sd;
      species_coeff_sd = DUMMY_VAR__;
      
      current_statement__ = 5;
      species_coeff_sd = in__.scalar();
      current_statement__ = 5;
      if (jacobian__) {
        current_statement__ = 5;
        species_coeff_sd = stan::math::lb_constrain(species_coeff_sd, 0, lp__);
      } else {
        current_statement__ = 5;
        species_coeff_sd = stan::math::lb_constrain(species_coeff_sd, 0);
      }
      local_scalar_t__ species_power_mean;
      species_power_mean = DUMMY_VAR__;
      
      current_statement__ = 6;
      species_power_mean = in__.scalar();
      local_scalar_t__ species_power_sd;
      species_power_sd = DUMMY_VAR__;
      
      current_statement__ = 7;
      species_power_sd = in__.scalar();
      current_statement__ = 7;
      if (jacobian__) {
        current_statement__ = 7;
        species_power_sd = stan::math::lb_constrain(species_power_sd, 0, lp__);
      } else {
        current_statement__ = 7;
        species_power_sd = stan::math::lb_constrain(species_power_sd, 0);
      }
      local_scalar_t__ global_error_sigma;
      global_error_sigma = DUMMY_VAR__;
      
      current_statement__ = 8;
      global_error_sigma = in__.scalar();
      current_statement__ = 8;
      if (jacobian__) {
        current_statement__ = 8;
        global_error_sigma = stan::math::lb_constrain(global_error_sigma, 0,
                               lp__);
      } else {
        current_statement__ = 8;
        global_error_sigma = stan::math::lb_constrain(global_error_sigma, 0);
      }
      {
        current_statement__ = 29;
        validate_non_negative_index("y_hat", "n_obs", n_obs);
        std::vector<local_scalar_t__> y_hat;
        y_hat = std::vector<local_scalar_t__>(n_obs, DUMMY_VAR__);
        
        Eigen::Matrix<local_scalar_t__, -1, 1> pars;
        pars = Eigen::Matrix<local_scalar_t__, -1, 1>(2);
        stan::math::fill(pars, DUMMY_VAR__);
        
        current_statement__ = 43;
        for (int i = 1; i <= n_obs; ++i) {
          current_statement__ = 32;
          assign(pars, cons_list(index_uni(1), nil_index_list()),
            ind_coeff[(ind_id[(i - 1)] - 1)], "assigning variable pars");
          current_statement__ = 33;
          assign(pars, cons_list(index_uni(2), nil_index_list()),
            ind_power[(ind_id[(i - 1)] - 1)], "assigning variable pars");
          current_statement__ = 36;
          if (logical_eq(obs_index[(i - 1)], 1)) {
            current_statement__ = 34;
            assign(y_hat, cons_list(index_uni(i), nil_index_list()),
              ind_y_0[(ind_id[(i - 1)] - 1)], "assigning variable y_hat");
          } 
          current_statement__ = 41;
          if (logical_lt(i, n_obs)) {
            current_statement__ = 39;
            if (logical_eq(ind_id[((i + 1) - 1)], ind_id[(i - 1)])) {
              current_statement__ = 37;
              assign(y_hat, cons_list(index_uni((i + 1)), nil_index_list()),
                rk4(y_hat[(i - 1)], y_bar[(ind_id[(i - 1)] - 1)], pars,
                  (time[((i + 1) - 1)] - time[(i - 1)]),
                  step_size, pstream__), "assigning variable y_hat");
            } 
          } }
        current_statement__ = 44;
        lp_accum__.add(
          normal_lpdf<propto__>(y_obs, y_hat, global_error_sigma));
        current_statement__ = 45;
        lp_accum__.add(
          normal_lpdf<propto__>(ind_y_0, y_0_obs, global_error_sigma));
        current_statement__ = 46;
        lp_accum__.add(
          lognormal_lpdf<propto__>(ind_coeff, species_coeff_mean,
            species_coeff_sd));
        current_statement__ = 47;
        lp_accum__.add(
          lognormal_lpdf<propto__>(ind_power, species_power_mean,
            species_power_sd));
        current_statement__ = 48;
        lp_accum__.add(normal_lpdf<propto__>(species_coeff_mean, 0, 2));
        current_statement__ = 49;
        lp_accum__.add(cauchy_lpdf<propto__>(species_coeff_sd, 0, 2));
        current_statement__ = 50;
        lp_accum__.add(normal_lpdf<propto__>(species_power_mean, 0, 2));
        current_statement__ = 51;
        lp_accum__.add(cauchy_lpdf<propto__>(species_power_sd, 0, 2));
        current_statement__ = 52;
        lp_accum__.add(cauchy_lpdf<propto__>(global_error_sigma, 0, 5));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_power_multi_ind_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      std::vector<double> ind_y_0;
      ind_y_0 = std::vector<double>(n_ind, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        current_statement__ = 1;
        assign(ind_y_0, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable ind_y_0");}
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        current_statement__ = 1;
        assign(ind_y_0, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_constrain(ind_y_0[(sym1__ - 1)], 0),
          "assigning variable ind_y_0");}
      std::vector<double> ind_coeff;
      ind_coeff = std::vector<double>(n_ind, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        current_statement__ = 2;
        assign(ind_coeff, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable ind_coeff");}
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        current_statement__ = 2;
        assign(ind_coeff, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_constrain(ind_coeff[(sym1__ - 1)], 0),
          "assigning variable ind_coeff");}
      std::vector<double> ind_power;
      ind_power = std::vector<double>(n_ind, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        current_statement__ = 3;
        assign(ind_power, cons_list(index_uni(sym1__), nil_index_list()),
          in__.scalar(), "assigning variable ind_power");}
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        current_statement__ = 3;
        assign(ind_power, cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_constrain(ind_power[(sym1__ - 1)], 0),
          "assigning variable ind_power");}
      double species_coeff_mean;
      species_coeff_mean = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      species_coeff_mean = in__.scalar();
      double species_coeff_sd;
      species_coeff_sd = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      species_coeff_sd = in__.scalar();
      current_statement__ = 5;
      species_coeff_sd = stan::math::lb_constrain(species_coeff_sd, 0);
      double species_power_mean;
      species_power_mean = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 6;
      species_power_mean = in__.scalar();
      double species_power_sd;
      species_power_sd = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 7;
      species_power_sd = in__.scalar();
      current_statement__ = 7;
      species_power_sd = stan::math::lb_constrain(species_power_sd, 0);
      double global_error_sigma;
      global_error_sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 8;
      global_error_sigma = in__.scalar();
      current_statement__ = 8;
      global_error_sigma = stan::math::lb_constrain(global_error_sigma, 0);
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        vars__.emplace_back(ind_y_0[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        vars__.emplace_back(ind_coeff[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        vars__.emplace_back(ind_power[(sym1__ - 1)]);}
      vars__.emplace_back(species_coeff_mean);
      vars__.emplace_back(species_coeff_sd);
      vars__.emplace_back(species_power_mean);
      vars__.emplace_back(species_power_sd);
      vars__.emplace_back(global_error_sigma);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      std::vector<double> y_hat;
      y_hat = std::vector<double>(n_obs, std::numeric_limits<double>::quiet_NaN());
      
      std::vector<double> Delta_hat;
      Delta_hat = std::vector<double>(n_obs, std::numeric_limits<double>::quiet_NaN());
      
      Eigen::Matrix<double, -1, 1> pars;
      pars = Eigen::Matrix<double, -1, 1>(2);
      stan::math::fill(pars, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 28;
      for (int i = 1; i <= n_obs; ++i) {
        current_statement__ = 12;
        assign(pars, cons_list(index_uni(1), nil_index_list()),
          ind_coeff[(ind_id[(i - 1)] - 1)], "assigning variable pars");
        current_statement__ = 13;
        assign(pars, cons_list(index_uni(2), nil_index_list()),
          ind_power[(ind_id[(i - 1)] - 1)], "assigning variable pars");
        current_statement__ = 16;
        if (logical_eq(obs_index[(i - 1)], 1)) {
          current_statement__ = 14;
          assign(y_hat, cons_list(index_uni(i), nil_index_list()),
            ind_y_0[(ind_id[(i - 1)] - 1)], "assigning variable y_hat");
        } 
        current_statement__ = 26;
        if (logical_lt(i, n_obs)) {
          current_statement__ = 24;
          if (logical_eq(ind_id[((i + 1) - 1)], ind_id[(i - 1)])) {
            current_statement__ = 21;
            assign(y_hat, cons_list(index_uni((i + 1)), nil_index_list()),
              rk4(y_hat[(i - 1)], y_bar[(ind_id[(i - 1)] - 1)], pars,
                (time[((i + 1) - 1)] - time[(i - 1)]), step_size, pstream__),
              "assigning variable y_hat");
            current_statement__ = 22;
            assign(Delta_hat, cons_list(index_uni(i), nil_index_list()),
              (y_hat[((i + 1) - 1)] - y_hat[(i - 1)]),
              "assigning variable Delta_hat");
          } else {
            current_statement__ = 19;
            assign(Delta_hat, cons_list(index_uni(i), nil_index_list()),
              (DE(y_hat[(i - 1)], y_bar[(ind_id[(i - 1)] - 1)],
                 pars, pstream__) * (time[(i - 1)] - time[((i - 1) - 1)])),
              "assigning variable Delta_hat");
          }
        } else {
          current_statement__ = 17;
          assign(Delta_hat, cons_list(index_uni(i), nil_index_list()),
            (DE(y_hat[(i - 1)], y_bar[(ind_id[(i - 1)] - 1)],
               pars, pstream__) * (time[(i - 1)] - time[((i - 1) - 1)])),
            "assigning variable Delta_hat");
        }}
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        vars__.emplace_back(y_hat[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        vars__.emplace_back(Delta_hat[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        vars__.emplace_back(pars[(sym1__ - 1)]);}
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      std::vector<double> ind_y_0;
      ind_y_0 = std::vector<double>(n_ind, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      assign(ind_y_0, nil_index_list(), context__.vals_r("ind_y_0"),
        "assigning variable ind_y_0");
      std::vector<double> ind_y_0_free__;
      ind_y_0_free__ = std::vector<double>(n_ind, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        current_statement__ = 1;
        assign(ind_y_0_free__,
          cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_free(ind_y_0[(sym1__ - 1)], 0),
          "assigning variable ind_y_0_free__");}
      std::vector<double> ind_coeff;
      ind_coeff = std::vector<double>(n_ind, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      assign(ind_coeff, nil_index_list(), context__.vals_r("ind_coeff"),
        "assigning variable ind_coeff");
      std::vector<double> ind_coeff_free__;
      ind_coeff_free__ = std::vector<double>(n_ind, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        current_statement__ = 2;
        assign(ind_coeff_free__,
          cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_free(ind_coeff[(sym1__ - 1)], 0),
          "assigning variable ind_coeff_free__");}
      std::vector<double> ind_power;
      ind_power = std::vector<double>(n_ind, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 3;
      assign(ind_power, nil_index_list(), context__.vals_r("ind_power"),
        "assigning variable ind_power");
      std::vector<double> ind_power_free__;
      ind_power_free__ = std::vector<double>(n_ind, std::numeric_limits<double>::quiet_NaN());
      
      current_statement__ = 3;
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        current_statement__ = 3;
        assign(ind_power_free__,
          cons_list(index_uni(sym1__), nil_index_list()),
          stan::math::lb_free(ind_power[(sym1__ - 1)], 0),
          "assigning variable ind_power_free__");}
      double species_coeff_mean;
      species_coeff_mean = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 4;
      species_coeff_mean = context__.vals_r("species_coeff_mean")[(1 - 1)];
      double species_coeff_sd;
      species_coeff_sd = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      species_coeff_sd = context__.vals_r("species_coeff_sd")[(1 - 1)];
      double species_coeff_sd_free__;
      species_coeff_sd_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 5;
      species_coeff_sd_free__ = stan::math::lb_free(species_coeff_sd, 0);
      double species_power_mean;
      species_power_mean = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 6;
      species_power_mean = context__.vals_r("species_power_mean")[(1 - 1)];
      double species_power_sd;
      species_power_sd = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 7;
      species_power_sd = context__.vals_r("species_power_sd")[(1 - 1)];
      double species_power_sd_free__;
      species_power_sd_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 7;
      species_power_sd_free__ = stan::math::lb_free(species_power_sd, 0);
      double global_error_sigma;
      global_error_sigma = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 8;
      global_error_sigma = context__.vals_r("global_error_sigma")[(1 - 1)];
      double global_error_sigma_free__;
      global_error_sigma_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 8;
      global_error_sigma_free__ = stan::math::lb_free(global_error_sigma, 0);
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        vars__.emplace_back(ind_y_0_free__[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        vars__.emplace_back(ind_coeff_free__[(sym1__ - 1)]);}
      for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
        vars__.emplace_back(ind_power_free__[(sym1__ - 1)]);}
      vars__.emplace_back(species_coeff_mean);
      vars__.emplace_back(species_coeff_sd_free__);
      vars__.emplace_back(species_power_mean);
      vars__.emplace_back(species_power_sd_free__);
      vars__.emplace_back(global_error_sigma_free__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("ind_y_0");
    names__.emplace_back("ind_coeff");
    names__.emplace_back("ind_power");
    names__.emplace_back("species_coeff_mean");
    names__.emplace_back("species_coeff_sd");
    names__.emplace_back("species_power_mean");
    names__.emplace_back("species_power_sd");
    names__.emplace_back("global_error_sigma");
    names__.emplace_back("y_hat");
    names__.emplace_back("Delta_hat");
    names__.emplace_back("pars");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n_ind)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n_ind)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n_ind)});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n_obs)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(n_obs)});
    
    dimss__.emplace_back(std::vector<size_t>{static_cast<size_t>(2)});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "ind_y_0" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "ind_coeff" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "ind_power" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "species_coeff_mean");
    param_names__.emplace_back(std::string() + "species_coeff_sd");
    param_names__.emplace_back(std::string() + "species_power_mean");
    param_names__.emplace_back(std::string() + "species_power_sd");
    param_names__.emplace_back(std::string() + "global_error_sigma");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_hat" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "Delta_hat" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "pars" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "ind_y_0" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "ind_coeff" + '.' + std::to_string(sym1__));
      }}
    for (int sym1__ = 1; sym1__ <= n_ind; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "ind_power" + '.' + std::to_string(sym1__));
      }}
    param_names__.emplace_back(std::string() + "species_coeff_mean");
    param_names__.emplace_back(std::string() + "species_coeff_sd");
    param_names__.emplace_back(std::string() + "species_power_mean");
    param_names__.emplace_back(std::string() + "species_power_sd");
    param_names__.emplace_back(std::string() + "global_error_sigma");
    if (emit_transformed_parameters__) {
      
    }
    
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "y_hat" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= n_obs; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "Delta_hat" + '.' + std::to_string(sym1__));
        }}
      for (int sym1__ = 1; sym1__ <= 2; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "pars" + '.' + std::to_string(sym1__));
        }}
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"ind_y_0\",\"type\":{\"name\":\"array\",\"length\":" << n_ind << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"ind_coeff\",\"type\":{\"name\":\"array\",\"length\":" << n_ind << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"ind_power\",\"type\":{\"name\":\"array\",\"length\":" << n_ind << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"species_coeff_mean\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"species_coeff_sd\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"species_power_mean\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"species_power_sd\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"global_error_sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_hat\",\"type\":{\"name\":\"array\",\"length\":" << n_obs << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"Delta_hat\",\"type\":{\"name\":\"array\",\"length\":" << n_obs << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"pars\",\"type\":{\"name\":\"vector\",\"length\":" << 2 << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"ind_y_0\",\"type\":{\"name\":\"array\",\"length\":" << n_ind << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"ind_coeff\",\"type\":{\"name\":\"array\",\"length\":" << n_ind << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"ind_power\",\"type\":{\"name\":\"array\",\"length\":" << n_ind << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"parameters\"},{\"name\":\"species_coeff_mean\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"species_coeff_sd\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"species_power_mean\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"species_power_sd\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"global_error_sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"y_hat\",\"type\":{\"name\":\"array\",\"length\":" << n_obs << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"Delta_hat\",\"type\":{\"name\":\"array\",\"length\":" << n_obs << ",\"element_type\":{\"name\":\"real\"}},\"block\":\"generated_quantities\"},{\"name\":\"pars\",\"type\":{\"name\":\"vector\",\"length\":" << 2 << "},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_power_multi_ind_namespace::model_power_multi_ind;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_power_multi_ind_namespace::profiles__;
}
#endif
#endif
