#' Run chosen pre-built model in Stan
#'
#' @param model_template model template generated by hmde_model and updated by hmde_assign_data
#' @param ... additional arguments passed to rstan::sampling
#'
#' @return Stanfit model output
#' @export

hmde_run <- function(model_template, ...) {

  # Detect model
  out <- switch(model_template$model,
         linear = rstan::sampling(stanmodels$linear, data = model_template, ...),
         constant_single_ind = rstan::sampling(stanmodels$constant_single_ind, data = model_template, ...),
         constant_multi_ind = rstan::sampling(stanmodels$constant_multi_ind, data = model_template, ...),
         canham_single_ind = rstan::sampling(stanmodels$canham_single_ind, data = model_template, ...),
         canham_multi_ind = rstan::sampling(stanmodels$canham_multi_ind, data = model_template, ...),
         power_single_ind = rstan::sampling(stanmodels$power_single_ind, data = model_template, ...),
         power_multi_ind = rstan::sampling(stanmodels$power_multi_ind, data = model_template, ...),
         vb_single_ind = rstan::sampling(stanmodels$vb_single_ind, data = model_template, ...),
         vb_multi_ind = rstan::sampling(stanmodels$vb_multi_ind, data = model_template, ...),
         linear_single_ind = rstan::sampling(stanmodels$linear_single_ind, data = model_template, ...))

  return(out)
}
