#' Run a linear model in Stan
#'
#' @param model_template model template generated by rmot_model and updated by rmot_assign_data
#' @param ... additional arguments passed to rstan::sampling
#'
#' @return Stanfit model output
#' @export
#'
#' @examples
#' rmot_model("linear") |>
#'   rmot_assign_data(X = Loblolly$age,
#'                    Y = Loblolly$height,
#'                    N = nrow(Loblolly)) |>
#'   rmot_run()
rmot_run <- function(model_template, ...) {

  # Detect model
  out <- switch(model_template$model,
         linear = rstan::sampling(stanmodels$linear, data = model_template, ...),
         constant_single_ind = rstan::sampling(stanmodels$constant_single_ind, data = model_template, ...),
         constant_multi_ind = rstan::sampling(stanmodels$constant_multi_ind, data = model_template, ...))

  return(out)
}
